### ISSUE TITLE
Docker toolbox: Machine, Compose, and Swarm

### ISSUE THREAD

**Issue by timqian** [timqian/my-notes#140]
- Machine: set up container hosts 
- Compose: run containers on container hosts
- Swarm: deploy container hosts as a cluster

## Docker Machine
Create container hosts on many of the most popular Infrastructure-as-a-Service platforms including: 
VMware Fusion and VirtualBox, AWS, Azure, DigitalOcean, Exoscale, Google Compute Engine, OpenStack, RackSpace, SoftLayer, VMware vSphere, and vCloud Air.
```bash
# Sample usage to create a container host using VirtualBox driver
docker-machine create --driver virtualbox containerhost 
```

## Docker Compose
Running some useful containers on container host. Define container info using `docker-compose.yml`
```yml
# Example docker-compose.yml
# The application is built using two containers web and redis
# To run: `docker-compose up`
web: 
  build: . # built from a Dockerfile in the current working directory
  ports: # shows which ports will be exposed on the host and which port the traffic will be forwarded to into the container
    - "5000:5000" 
  volumes: # mount a Docker volume into the container, containing the application code. 
    - .:/code 
  links:  # link to another container
    - redis 
redis: 
  image: redis
```

## Docker swarm
turn that small test environment into a larger setup of clustered container hosts that can be used to scale your operations

## Ref
- [A little outdated but conceptually right](https://blog.codeship.com/docker-machine-compose-and-swarm-how-they-work-together/)
- [A step by step guide to swarm on AWS](https://gist.github.com/ghoranyi/f2970d6ab2408a8a37dbe8d42af4f0a5)
