### ISSUE TITLE
css 布局

### ISSUE THREAD

**Issue by timqian** [timqian/my-notes#75]
## position

```css
.container {
  position: relative;
}
nav {
  position: absolute;
  left: 0px;
  width: 200px;
}
section {
  /* position is static by default */
  margin-left: 200px;
}
body {
  margin-bottom: 120px;
}
```

## float
```css
nav {
  float: left;
  width: 200px;
}
section {
  margin-left: 200px;
}
```

## inline-box
```css
nav {
  display: inline-block;
  vertical-align: top;
  width: 25%;
}
.column {
  display: inline-block;
  vertical-align: top;
  width: 75%;
}
```

## flexbox
```css
.container {
  display: flex;
}
nav {
  width: 200px;
}
.flex-column {
   flex: 1;
}
```
